### ISSUE TITLE
Support `Array#findLast` and `Array#findLastIndex`

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#1891]
They have reached stage 4. https://github.com/tc39/proposal-array-find-from-last#status

TODOs:

- [x] `no-array-callback-reference` #1889
- [x] `no-array-method-this-argument` #1890
- [x] `prefer-array-find` should check `filter().at(-1)` #1900
- [x] `prefer-array-index-of` should check `.findLastIndex()` #1896
- [x] `prefer-array-some` should check `.findLast` #1897
- [x] ~`prefer-includes` should check `findLastIndex`~ (~We didn't check `findIndex`, so maybe not, need investigate~)No change needed
- [x] `prefer-native-coercion-functions` should check both #1893
- [x] `prefer-prototype-methods` should check both #1898

**Comment by fisker** [comment]
Prefer `.findLast` over `.filter().at(-1)` can't simply add to `prefer-array-find` as #1896, since engine may not support it yet, we need an option.

**Comment by fisker** [comment]
Should the option name be `preferFindLast` ?

**Comment by sindresorhus** [comment]
`checkFromLast`

**Comment by fisker** [comment]
All PRs merged.
